image: ruby:2.7

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install
  - apt-get -qq update
  - apt-get -qq install -y lftp

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public -b "/pf2-jekyll/"
  - bundle exec jekyll build -d pf-org
  - lftp -e "open pathfinder-fr.org; user $ftp_username $ftp_password; mirror --reverse --verbose --delete pf-org/ /; bye"
  artifacts:
    paths:
    - pf-org
  only:
  - master
