image: ruby:2.7

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public -b "/pf2-jekyll/"
  - bundle exec jekyll build -d pf-org
  artifacts:
    paths:
    - public
  only:
  - master
