image: ruby:2.7

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

# utilisation d'un cache réutilisable pour accéler les déploiements
# le cache est spécifique par job (pages, pf-org) et par branche
#
# .jekyll-cache : données de jekyll
# .vendor : packages ruby
# public/ et /pf-org/ : fichiers en sortie du site, pour la gestion de --incremental
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  when: always
  paths:
    - .jekyll-cache/
    - .vendor/
    - public/
    - pf-org/

before_script:
  - bundle config set path '.vendor'
  - bundle install
  - apt-get -qq update
  - apt-get -qq install -y lftp

# build interne pour gitlab-pages
# https://pathfinder-fr.gitlab.io/pf2-jekyll/
pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public -b "/pf2-jekyll/" --verbose --incremental
  artifacts:
    paths:
    - public
  only:
  - master
  interruptible: true

# build officielle pour le site pathfinder-fr.org
pf-org:
  stage: build
  script:
  - bundle exec jekyll build -d pf-org --incremental
  artifacts:
    paths:
    - pf-org
  only:
  - pub
  interruptible: true

# déploiement officiel (FTP) pour le site pathfinder-fr.org
# https://www.pathfinder-fr.org/srd/pf2
deploy:
  stage: deploy
  script:
  - lftp -e "set ssl:verify-certificate no; set mirror:overwrite true; set mirror:parallel-transfer-count 5; open pathfinder-fr.org; user $ftp_username $ftp_password; mirror --reverse --delete --use-cache --no-perms --no-umask --overwrite --only-newer pf-org/ /; bye"
  only:
  - pub
  interruptible: true