image: ruby:2.7

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install
  - apt-get -qq update
  - apt-get -qq install -y lftp

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public -b "/pf2-jekyll/"
  artifacts:
    paths:
    - public
  only:
  - master

pf-org:
  stage: deploy
  script:
  - bundle exec jekyll build -d pf-org
  - lftp -e "set ssl:verify-certificate no; set ftps:initial-prot P; set mirror:overwrite true; set mirror:parallel-transfer-count 5; open pathfinder-fr.org; user $ftp_username $ftp_password; mirror -R -e --use-cache --ignore-time pf-org/ /; bye"
  artifacts:
    paths:
    - pf-org
  only:
  - pub
