image: ruby:2.7

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

# utilisation d'un cache réutilisable pour accéler les déploiements
# le cache est spécifique par job (pages, pf-org) et par branche
#
# .jekyll-cache : données de jekyll
# .vendor : packages ruby
# public/ et /pf-org/ : fichiers en sortie du site, pour la gestion de --incremental
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  when: always
  paths:
    - .jekyll-cache/
    - .vendor/
    - public/
    - pf-org/

before_script:
  - bundle config set path '.vendor'
  - bundle install
  - apt-get -qq update
  - apt-get -qq install -y lftp

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public --incremental -b "/pf2-jekyll/"
  artifacts:
    paths:
    - public
  only:
  - master

pf-org:
  stage: deploy
  script:
  - bundle exec jekyll build -d pf-org --incremental
  - lftp -e "set ssl:verify-certificate no; set ftps:initial-prot P; set mirror:overwrite true; set mirror:parallel-transfer-count 5; open pathfinder-fr.org; user $ftp_username $ftp_password; mirror -R -e --use-cache pf-org/ /; bye"
  artifacts:
    paths:
    - pf-org
  only:
  - pub
